---

- name: "enable traefik systemd unit"
  become: true
  ansible.builtin.systemd:
    name: traefik
    enabled: yes
    masked: 'no'
    daemon_reload: yes

- name: "restart traefik systemd unit"
  become: true
  ansible.builtin.systemd:
    state: "restarted"
    name: "traefik"
    daemon_reload: yes
